### ISSUE TITLE
Geolocator doesnt works side by side with onesignal

### ISSUE THREAD

**Issue by vinicioslc** [BaseflowIT/flutter-geolocator#124]
## 🐛 Bug Report
Simply add the [onesignal](https://pub.dartlang.org/packages/onesignal) package to the sample project, configure correctly the two geolocator packages and run on a device and BOOM the trick happens

App crashes...

### Expected behavior
Run the app 
### Reproduction steps
Add the latest onesignal package (oficial or community) from pub packages and run the app, him will crash....
### Configuration
dont need...
My pubspec
```
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  onesignal: ^1.0.2
  geolocator: ^2.0.1
```
**Version:** ^2.0.1

**Platform:** 
- [] :iphone: iOS
- [x] :robot: Android
